{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units_LSTM_1", "default": null, "conditions": [], "min_value": 50, "max_value": 200, "step": 50, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_1", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_LSTM_2", "default": null, "conditions": [], "min_value": 50, "max_value": 200, "step": 50, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_2", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 10, "max_value": 50, "step": 10, "sampling": "linear"}}], "values": {"units_LSTM_1": 100, "dropout_1": 0.30000000000000004, "units_LSTM_2": 100, "dropout_2": 0.30000000000000004, "dense_units": 20}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 173, in _try_build\n    size = maybe_compute_model_size(model)\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 463, in maybe_compute_model_size\n    params = [math.prod(p.shape) for p in model.trainable_weights]\n  File \"C:\\Users\\grego\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 463, in <listcomp>\n    params = [math.prod(p.shape) for p in model.trainable_weights]\nAttributeError: module 'math' has no attribute 'prod'\n"}